##  Name of the workflow.
name: TechTrends - Package with Docker
## Set the trigger policy.
on:
  push:
    branches: [main]
## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  check-python-version:
    ## Configure the operating system the workflow should run on.
    ## In this case, the job on Ubuntu
    runs-on: ubuntu-latest
    ## Define a sequence of steps to be executed
    steps:
      ## Use the public `checkout` action in version v2
      ## to checkout the existing code in the repository
      - name: checkout repo
        uses: actions/checkout@v2
      ## Use the public `setup-python` action  in version v2
      ## to install python on the  Ubuntu based environment
      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Dockerbuild
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./project/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/techtrends:latest